### ISSUE TITLE
AttributeError: 'CartpoleRobot' object has no attribute 'getSelf'

### ISSUE THREAD

**Issue by ahforoughi** [aidudezzz/deepbots-tutorials#17]
Hi 
I follow instructions in the repo but got this error:

```python
Traceback (most recent call last): \
  File "supervisorController.py", line 84, in <module>
    env = CartpoleRobot()
  File "supervisorController.py", line 15, in __init__
    self.robot = self.getSelf()  # Grab the robot reference from the supervisor to access various robot methods
AttributeError: 'CartpoleRobot' object has no attribute 'getSelf'
WARNING: 'supervisorController' controller exited with status: 1.
```

**Comment by tsampazk** [comment]
Hello @ahforoughi, thank you for bringing this issue to our attention!

The tutorial targets the newest version of deepbots that is currently not released and changes in that version cause this issue.

I will add a notice in the tutorial until the new release.

For now you can install the dev version of  deepbots from [here](https://test.pypi.org/project/deepbots/) with the following command:
`pip install -i https://test.pypi.org/simple/ deepbots`
Note that the version is in development and some features such as the wrappers are not functioning properly.

Otherwise, you can make the following changes in your `__init__` method to fix the problem using the current deepbots release,
i marked the changed lines in the comments:
```python
        self.robot = self.supervisor.getSelf()  # Fix
        self.positionSensor = self.supervisor.getDevice("polePosSensor")  # Fix
        self.positionSensor.enable(self.timestep)

        self.poleEndpoint = self.supervisor.getFromDef("POLE_ENDPOINT")  # Fix
        self.wheels = []
        for wheelName in ['wheel1', 'wheel2', 'wheel3', 'wheel4']:
            wheel = self.supervisor.getDevice(wheelName)  # Fix
```

Let me know if it works for you and feel free to ask any additional questions! 😄

**Comment by cwjwudi** [comment]
After I use your way to fix the problem,there is still a problem.
`Traceback (most recent call last):
  File "robotSupervisorController.py", line 96, in <module>
    env = CartpoleRobot()
  File "robotSupervisorController.py", line 23, in __init__
    self.positionSensor.enable(self.timestep)
AttributeError: 'NoneType' object has no attribute 'enable'`

**Comment by ManosMagnus** [comment]
What's the name of your `poleEndpont`? The name defined in simulator for the endpoint should be the same as in your code 
 
`self.poleEndpoint = self.supervisor.getFromDef("<name>")`

**Comment by cwjwudi** [comment]
> What's the name of your `poleEndpont`? The name defined in simulator for the endpoint should be the same as in your code
> 
> `self.poleEndpoint = self.supervisor.getFromDef("<name>")`

Hi, I've fix the problem, in my environment, the `getDevice`did not work properly. Finally, I found that change the `self.positionSensor = self.getDevice('polePosSensor')` into `self.positionSensor = self.getPositionSensor('polePosSensor')` and `wheel = self.getDevice(wheelName)` into `wheel = self.getMotor(wheelName)wheel = self.getMotor(wheelName)`.
My, environment is `Ubuntu 18.04` ,`Python 3.7.10` , `Webots 2021`
