### ISSUE TITLE
A question about the method "self.robot.getPosition()"

### ISSUE THREAD

**Issue by wilhem** [aidudezzz/deepbots-tutorials#42]
Hi,

I'm trying to use deepbots in my enviroment. Since my robot has 5 DoFs and it is not a cartpole one I thought, I can use the method `getPosition()`, which inherited from `self.getSelf()`.
Bu then I realize, that no matter one many parts my robot contains. The method delivers all the time an array (or list) with three element:
`[0.0 0.0 0.0]`

Doesn't read that method how many "joints" are present in the robots?

**Comment by tsampazk** [comment]
I am not exactly certain about what your issue is. The Webots documentation found [here](https://cyberbotics.com/doc/reference/supervisor?tab-language=python#wb_supervisor_node_get_position) can be helpful.

In the tutorial, the `self.robot.getPosition` method is called to construct the observation. This method returns the node's, i.e. the robot's, world position coordinates. Your robot sounds like it is much more complicated.

If you have joints and you want to get their positions, e.g. the angle they are rotated currently, you need to add position sensors to them and get the sensors' values, as done on the cartpole robot pole. You can see the robot definition [here](https://github.com/aidudezzz/deepbots-tutorials/blob/48f76ecc9791d6b9cfc415623b4ad30d208efc9c/robotSupervisorSchemeTutorial/full_project/controllers/robot_supervisor_controller/cartpole_robot_definition.txt#L132-L144) and check the node tree in the Webots UI when you have the project open, through looking into the robot node's children. Then the sensor is initialized [here](https://github.com/aidudezzz/deepbots-tutorials/blob/48f76ecc9791d6b9cfc415623b4ad30d208efc9c/robotSupervisorSchemeTutorial/full_project/controllers/robot_supervisor_controller/robot_supervisor_controller.py#L19-L21) and its value is read [here](https://github.com/aidudezzz/deepbots-tutorials/blob/48f76ecc9791d6b9cfc415623b4ad30d208efc9c/robotSupervisorSchemeTutorial/full_project/controllers/robot_supervisor_controller/robot_supervisor_controller.py#L40). You can read more on Webots joints on their documentation i linked above.

I hope this proves helpful.

**Comment by wilhem** [comment]
Thank you for your reply.
I got it.... 
The method getPosition() delivers the three spatial coordinates (x, y, z). But at the very beginning I thought, it gave the three joints values (like: [angle_1, angle_2, distance_1]).
Thank your for your reply.
By the way: I'm using Webots since few weeks and what I missed was the possibility to use RL on it (I tried by coupling it to ROS2 but is not easy).
Thank you very much for your work with deepbots. Your word is - still - underappreciated. I'm sure that more and more people are going to use it. I'm so happy, that I found it.

**Comment by tsampazk** [comment]
> Thank you for your reply. I got it.... The method getPosition() delivers the three spatial coordinates (x, y, z). But at the very beginning I thought, it gave the three joints values (like: [angle_1, angle_2, distance_1]). Thank your for your reply. By the way: I'm using Webots since few weeks and what I missed was the possibility to use RL on it (I tried by coupling it to ROS2 but is not easy). 

Happy to help! To be honest i don't have experience coupling Webots to ROS, the official repo might help you https://github.com/cyberbotics/webots_ros2?tab=readme-ov-file

> Thank you very much for your work with deepbots. Your word is - still - underappreciated. I'm sure that more and more people are going to use it. I'm so happy, that I found it.

Thank you so much for your kind words @wilhem! :heart_hands:
